server.port=8080
spring.application.name=demo-micro

# Se sobreescribe en tiempo de ejecucion con la variable de entorno APP_VERSION
app.version=${APP_VERSION:local}

# Endpoints de salud para K8s / Docker healthcheck
management.endpoints.web.exposure.include=health,info
management.endpoint.health.probes.enabled=true
